# Generated by Django 3.2 on 2022-07-18 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oddam', '0002_auto_20220718_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='oddam.Category', verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='opis'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='liczba worków')),
                ('address', models.CharField(max_length=256, verbose_name='adres')),
                ('phone_number', models.IntegerField(max_length=9, verbose_name='numer telefonu')),
                ('city', models.CharField(max_length=64, verbose_name='miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='godzina odbioru')),
                ('pick_up_comment', models.CharField(max_length=500, verbose_name='komentarz')),
                ('categories', models.ManyToManyField(to='oddam.Category', verbose_name='kategoria')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddam.institution', verbose_name='organizacja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='darczyńca')),
            ],
        ),
    ]
