# Generated by Django 3.2 on 2022-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0003_auto_20220718_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(verbose_name='numer telefonu'),
        ),
    ]
