# Generated by Django 3.2 on 2022-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0004_alter_donation_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Organizcja charytatywna', 'verbose_name_plural': 'Organizacje charytatywne'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
